# Generated by Django 3.1.7 on 2021-03-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stroke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.FloatField()),
                ('ever_married', models.FloatField()),
                ('work_type', models.FloatField()),
                ('Residence_type', models.FloatField()),
                ('smoking_status', models.FloatField()),
                ('age', models.FloatField()),
                ('hypertension', models.FloatField()),
                ('heart_disease', models.FloatField()),
                ('avg_glucose_level', models.FloatField()),
                ('bmi', models.FloatField()),
            ],
        ),
    ]
